Give me a broad (The Data Cleaning Game Plan) for me to clean any file types in interview for DE fresher and also self skill to clean any dataset. So give me the process and functions list

Having a systematic approach to data cleaning is exactly what hiring managers look for in Data Engineering interviews. They want to see that you do not just blindly execute code, but that you investigate, plan, and standardize.

Here is your universal blueprint for tackling any raw dataset.

## The Universal Data Cleaning Game Plan
### Phase 1: Assess & Profile (The Reconnaissance)
Never modify data before understanding its shape. Your first goal is to spot anomalies, missing values, and incorrect data types.

* Check the footprint: How many rows and columns exist? Are numbers accidentally stored as strings?

* Identify missingness: Are null values random, or is an entire column completely empty?

* Spot weird placeholders: Look for "UNKNOWN", "N/A", "9999", or "ERROR" masquerading as valid data.

### Phase 2: Structural & Type Cleaning (The Foundation)
* Once you know what is broken, fix the structural shell of the DataFrame before altering individual cell values.

* Standardize headers: Convert all column names to lowercase snake_case (e.g., Price Per Unit to price_per_unit) so they are database-ready.

* Drop pure duplicates: Remove identical rows immediately to prevent skewed downstream aggregations.

* Cast strict types: Force columns into their proper formats (e.g., converting a string date into a DateTime object, or a string price into a float).

### Phase 3: Text & Value Standardization (The Polish)
* This is where you use your Regex and string manipulation skills to clean the actual data payload.

* Impute or drop nulls: Decide whether to fill missing values with a default/median value or drop the row entirely.

* Vectorized string cleaning: Strip hidden whitespace and standardize capitalization across all categorical text.

* Unify categories: Group similar variations together (e.g., merging "CreditCard", "credit card", and "CC" into a single "credit_card" category).

## Your Core Pandas Toolkit
Here are the primary vectorized functions you will rely on to execute this game plan:

#### Cleaning Phase	Essential Pandas Functions
1. Assess :   .info(), .describe(), .isnull().sum(), .value_counts()
2. Structure :   .rename(), .drop_duplicates(), .astype(), pd.to_datetime()
3. Values :   .fillna(), .dropna(), .replace(), .map()
4. Strings :   .str.strip(), .str.lower(), .str.extract(), .str.replace()
If you internalize this workflow, you can confidently take any messy file from a raw state to a production-ready table.

Would you like to put this framework to the test and practice executing Phase 1 (Assess & Profile) on a brand new, uncleaned dataset?

Here explain the important pandas functions and explain them in detail with neat example

To master data cleaning, you need to understand exactly what your tools do behind the scenes. Let's break down the most essential Pandas functions step-by-step using a brand-new, messy dummy dataset.

You can copy this into a new cell to follow along:

Python
import pandas as pd

* A purposefully messy dataset
data = {
    'Cust_Name ': ['Alice', 'Bob', 'Alice', 'DAVE', 'eve  '],
    ' Age': ['25', 'ERROR', '25', '30', np.nan],
    'Join Date': ['2023-01-15', '2023-02-20', '2023-01-15', 'UNKNOWN', '2023-05-10']
}
df = pd.DataFrame(data)
1. Assessing the Data (The Detective Work)
Before you change anything, you must understand what is broken.

df.info()

What it does: Gives you the "blueprint" of your DataFrame. It tells you the total number of rows, the exact column names, how many non-null (non-empty) values exist in each column, and the data types.

Why it's crucial: If your "Age" column is supposed to be numbers, but .info() says it is an object (string), you instantly know you have bad data hidden in there (like the word "ERROR").

Python
df.info() 
df['column'].value_counts()

What it does: Counts how many times each unique value appears in a specific column.

Why it's crucial: It exposes weird placeholders. If you run this on a "Status" column and see Success: 500, Failed: 20, and 999: 5, you instantly know 999 is a garbage value that needs cleaning.

Python
df[' Age'].value_counts() # Will reveal the word 'ERROR' hiding among numbers

2. Structural Cleaning (Fixing the Shell)
Now we fix the shape and structure of the table itself.

df.rename(columns={})

What it does: Changes column headers using a dictionary where the "key" is the old name and the "value" is the new name.

Why it's crucial: Notice how our dummy data has Cust_Name  (with a trailing space) and  Age (with a leading space)? Trying to code with those spaces is a nightmare.

Python
* Rename columns to standard lowercase snake_case
df = df.rename(columns={
    'Cust_Name ': 'cust_name', 
    ' Age': 'age', 
    'Join Date': 'join_date'
})
df.drop_duplicates()

What it does: Scans the entire DataFrame and completely removes any row that is an exact, 100% clone of another row.

Why it's crucial: Duplicate rows will mathematically ruin aggregations (like sums and averages).

Python
* Drops the second 'Alice' row because it is an exact clone of the first
df = df.drop_duplicates()
 
3. Value Cleaning (Fixing the Payload)
This is where we replace bad placeholders and handle the missing gaps.

df['column'].replace()

What it does: Swaps specific targeted values for new ones.

Why it's crucial: We need to turn words like "ERROR" or "UNKNOWN" into actual math-friendly null values (np.nan) so Pandas knows they are officially blank.

Python
* Replace string placeholders with actual Null values
df['age'] = df['age'].replace('ERROR', np.nan)
df['join_date'] = df['join_date'].replace('UNKNOWN', None)
df['column'].fillna()

What it does: Finds every officially blank cell (NaN / None) and fills it with a value of your choice.

Why it's crucial: If you try to do math on a column with NaN values, it will often break. You can fill gaps with a hardcoded number (like 0), or a calculated metric.

Python
* Fill missing ages with the number 0
df['age'] = df['age'].fillna(0)

4. Text & Type Cleaning (The Final Polish)
Now we fix the messy capitalization and force the columns into the correct data formats.

df['column'].str.strip() and .str.title()

What it does: .strip() deletes invisible spaces at the start and end of strings. .title() capitalizes the first letter of every word.

Why it's crucial: In a database, "eve" and "Eve " are considered two entirely different people. We must standardize them.

Python
* Method Chaining: Strip spaces, then title case the names
df['cust_name'] = df['cust_name'].str.strip().str.title()
df['column'].astype()

What it does: Forces a column to become a specific mathematical data type (like an integer int or a decimal float).

Why it's crucial: Now that we replaced the word "ERROR" and filled our nulls, we can safely convert the Age column from text strings into actual numbers.

Python
df['age'] = df['age'].astype(int)
pd.to_datetime()

What it does: Converts text strings that look like dates into actual, calculable Pandas Timestamp objects.

Why it's crucial: If dates are left as strings, you cannot sort them chronologically or calculate the difference between two dates (like "days since joined").

Python
df['join_date'] = pd.to_datetime(df['join_date'])

In [166]:
import pandas as pd
import io

csv_data = """Order ID, Customer Name ,Product_Category,Price (USD),Qty,Order_Date
ORD-2824,UNKNOWN, Electronics,100, 4,08/02/2026
ORD-1409,Grace   , Electronics,100,3,04-08-2026
ORD-5506,bob,Clothing,100,five,08/02/2026
ORD-5012,UNKNOWN,Clothing,ERROR,1,04-08-2026
ORD-4657,UNKNOWN,unknown,$19.99,2,2026/08/03
ORD-3286,Eve,clothing ,$19.99,five,04-08-2026
ORD-2679,bob, Electronics,  50.5 ,2,2026-08-05
ORD-9935,  ,Clothing,ERROR,3,UNKNOWN
ORD-2424,Grace   ,  Toys,ERROR,-1,04-08-2026
ORD-7912,ERROR,unknown,N/A,five,04-08-2026
ORD-3286,  dave, ElecTRONICS,  50.5 , 4,2026-08-01
ORD-3406,UNKNOWN,HOME,0.0,UNKNOWN,2026/08/03
,CHARLIE,clothing ,$9.99,-1,pending
ORD-9204,  dave,unknown,$19.99,-1,2026-08-01
ORD-7685,  dave,HOME,$19.99,3,08/02/2026
ORD-5111,UNKNOWN,HOME,  50.5 ,1,04-08-2026
ORD-1981,  ,  Toys,100,1,08/02/2026
ORD-8772,UNKNOWN,HOME,$9.99, 4,UNKNOWN
ORD-2638,  dave,HOME,$9.99,10,08/02/2026
ORD-2487,UNKNOWN,unknown,0.0,2,04-08-2026
ORD-6679,bob, ElecTRONICS,25.50,3,04-08-2026
ORD-5660,  ,  Toys,100,five,04-08-2026
ORD-7235,  dave,clothing ,25.50,2,2026/08/03
ORD-6401,UNKNOWN, ElecTRONICS,ERROR,UNKNOWN,08/02/2026
ORD-8280,UNKNOWN,clothing ,$19.99,-1,2026-08-01
ORD-5026,, ElecTRONICS,  50.5 ,2,2026-08-01
ORD-4956,CHARLIE,clothing ,ERROR,3,04-08-2026
ORD-3549,  dave,  Toys,N/A,-1,2026-08-01
ORD-5369,  dave,unknown,$9.99,-1,2026-08-05
ORD-5612,  ,Clothing,$9.99,1,04-08-2026
ORD-2715,  dave,HOME,$9.99,2,2026-08-01
ORD-1017,  dave,  Toys,N/A,1,2026-08-05
ORD-5198,  ,  Toys,$19.99, 4,2026/08/03
ORD-8716,bob,HOME,100,10,08/02/2026
ORD-6680,  , ElecTRONICS,0.0,-1,04-08-2026
ORD-1157,UNKNOWN,HOME,25.50, 4,pending
ORD-4171,CHARLIE,  Toys,N/A,10,08/02/2026
ORD-7940,UNKNOWN,HOME,0.0,-1,04-08-2026
ORD-5706,UNKNOWN,unknown,N/A, 4,2026-08-05
ORD-4309,  , ElecTRONICS,  50.5 ,3,04-08-2026
ORD-8106,  dave,  Toys,N/A,3,UNKNOWN
ORD-3051,Grace   ,unknown,$9.99,10,UNKNOWN
ORD-3095,  dave, ElecTRONICS,0.0, 4,2026-08-05
ORD-7685,  dave,HOME,  50.5 ,3,2026-08-01
ORD-5407,  dave, ElecTRONICS,N/A,1,2026-08-05
ORD-5111,  ,  Toys,$19.99,2,UNKNOWN
ORD-2268,  dave,clothing ,25.50,1,04-08-2026
ORD-5872,CHARLIE,unknown,25.50,1,UNKNOWN
ORD-7080,Grace   ,unknown,  50.5 ,1,04-08-2026
ORD-6264,UNKNOWN,unknown,  50.5 ,3,UNKNOWN
ORD-8697,,  Toys,nan,3,04-08-2026
ORD-1845,  , ElecTRONICS,25.50,1,2026/08/03
ORD-4008,  ,HOME,0.0,-1,2026-08-01
ORD-8438,  dave,unknown,$9.99,3,04-08-2026
ORD-3323,UNKNOWN,clothing ,$9.99,2,UNKNOWN
ORD-9743,bob,unknown,$9.99,five,UNKNOWN
ORD-3331,  ,  Toys,N/A,1,2026-08-05
ORD-2975,  ,HOME,25.50,1,2026/08/03
ORD-9614,ERROR,clothing ,25.50,10,04-08-2026
ORD-2795,CHARLIE,clothing ,25.50, 4,04-08-2026
ORD-4491,  , ElecTRONICS,N/A,-1,2026/08/03
ORD-1903,CHARLIE,clothing ,ERROR,3,08/02/2026
ORD-2586,  ,unknown,$9.99,10,2026-08-01
ORD-4217,  , ElecTRONICS,$19.99,1,08/02/2026
ORD-8686,UNKNOWN,unknown,0.0,UNKNOWN,UNKNOWN
ORD-5484,  ,unknown,$9.99,10,2026-08-01
ORD-8717,  ,clothing ,100,10,08/02/2026
ORD-8515,  dave,unknown,$19.99, 4,04-08-2026
ORD-7053,Grace   ,unknown,25.50,five,2026-08-01
ORD-3453,UNKNOWN,unknown,N/A,five,2026/08/03
ORD-6825,  dave,HOME,  50.5 ,3,04-08-2026
ORD-4171,UNKNOWN, ElecTRONICS,ERROR,2,04-08-2026
ORD-8114,bob,unknown,$19.99,-1,pending
ORD-7940,UNKNOWN,HOME,0.0,-1,04-08-2026
ORD-9204,ERROR,  Toys,$9.99,UNKNOWN,UNKNOWN
ORD-3601,  , ElecTRONICS,$9.99,,pending
ORD-3135,Eve,HOME,0.0,2,08/02/2026
ORD-4217,  dave,HOME,  50.5 ,3,2026-08-05
ORD-6679,bob,HOME,25.50,-1,UNKNOWN
ORD-4560,UNKNOWN,unknown,$9.99,-1,UNKNOWN
ORD-8049,UNKNOWN,unknown,0.0,3,2026-08-01
ORD-7191,CHARLIE,clothing ,$9.99,-1,2026-08-05
ORD-1594,UNKNOWN,HOME,100,1,UNKNOWN
ORD-8947,  dave,HOME,$9.99,-1,2026-08-01
ORD-5353,Grace   , ElecTRONICS,25.50,five,pending
ORD-2465,  , ElecTRONICS,  50.5 ,2,pending
ORD-8326,UNKNOWN,HOME,100,five,2026-08-01
ORD-8072,  ,  Toys,  50.5 ,3,2026/08/03
ORD-6178,bob,HOME,ERROR,2,UNKNOWN
ORD-4161,  , ElecTRONICS,N/A,2,2026-08-01
ORD-8373,UNKNOWN,unknown,0.0,five,2026-08-01
ORD-7815,CHARLIE,unknown,100,3,UNKNOWN
ORD-5942,UNKNOWN,unknown,100,-1,2026-08-01
ORD-5360,Eve,  Toys,25.50,3,2026-08-05
ORD-8857,  dave,clothing ,ERROR,3,2026/08/03
ORD-4414,CHARLIE,HOME,100, 4,04-08-2026
ORD-4433,  , ElecTRONICS,$9.99,10,08/02/2026
ORD-7810,bob,unknown,$9.99,-1,04-08-2026
ORD-2158,UNKNOWN,clothing ,ERROR,10,04-08-2026
ORD-8677,Eve,unknown,ERROR,3,UNKNOWN
ORD-8677,Eve,unknown,ERROR,3,UNKNOWN
ORD-8677,Eve,HOME,0.0,UNKNOWN,08/02/2026
ORD-7463,  dave,clothing ,$9.99,2,2026-08-01
ORD-1175,bob,unknown,25.50,-1,08/02/2026
ORD-8285,Grace   ,HOME,0.0,1,08/02/2026
ORD-3129,Eve,  Toys,25.50,2,2026-08-01
ORD-1316,bob,unknown,$9.99,-1,04-08-2026
ORD-8260,  dave, ElecTRONICS,25.50, 4,2026-08-05
ORD-8761,  ,unknown,25.50,1,04-08-2026
ORD-9742,Grace   ,  Toys,0.0,1,pending
ORD-3406,  dave,unknown,  50.5 ,2,pending
ORD-6987,UNKNOWN, ElecTRONICS,100,3,UNKNOWN
ORD-6346,  dave,unknown,0.0,-1,04-08-2026
ORD-9069,  dave,  Toys,0.0,10,2026-08-05
ORD-5011,  , ElecTRONICS,25.50,3,08/02/2026
ORD-1773,  ,  Toys,  50.5 ,1,04-08-2026
ORD-3286,Eve,clothing ,$19.99,five,04-08-2026
ORD-6679,bob, ElecTRONICS,25.50,3,04-08-2026
ORD-7940,UNKNOWN,HOME,0.0,-1,04-08-2026
ORD-7940,UNKNOWN,HOME,0.0,-1,04-08-2026
"""

df = pd.read_csv(io.StringIO(csv_data))
df

     Order ID  Customer Name  Product_Category Price (USD)   Qty  Order_Date
0    ORD-2824         UNKNOWN      Electronics         100     4  08/02/2026
1    ORD-1409        Grace         Electronics         100     3  04-08-2026
2    ORD-5506             bob         Clothing         100  five  08/02/2026
3    ORD-5012         UNKNOWN         Clothing       ERROR     1  04-08-2026
4    ORD-4657         UNKNOWN          unknown      $19.99     2  2026/08/03
..        ...             ...              ...         ...   ...         ...
115  ORD-1773                             Toys       50.5      1  04-08-2026
116  ORD-3286             Eve        clothing       $19.99  five  04-08-2026
117  ORD-6679             bob      ElecTRONICS       25.50     3  04-08-2026
118  ORD-7940         UNKNOWN             HOME         0.0    -1  04-08-2026
119  ORD-7940         UNKNOWN             HOME         0.0    -1  04-08-2026

[120 rows x 6 columns]

#### Phase 1: Assess & Profile. You are now the detective.

In [139]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          119 non-null    str
 1    Customer Name    118 non-null    str
 2   Product_Category  120 non-null    str
 3   Price (USD)       108 non-null    str
 4   Qty               119 non-null    str
 5   Order_Date        120 non-null    str
dtypes: str(6)
memory usage: 5.8 KB

In [140]:
df.isnull().sum()

Order ID             1
 Customer Name       2
Product_Category     0
Price (USD)         12
Qty                  1
Order_Date           0
dtype: int64

In [141]:
df.duplicated().sum()

np.int64(6)

In [142]:
for col in df.columns:
    print(f"*****{col}*****")
    print(df[col].value_counts(dropna=False))
    print()

*****Order ID*****
Order ID
ORD-7940    4
ORD-3286    3
ORD-6679    3
ORD-8677    3
ORD-3406    2
           ..
ORD-6987    1
ORD-6346    1
ORD-9069    1
ORD-5011    1
ORD-1773    1
Name: count, Length: 105, dtype: int64

***** Customer Name *****
 Customer Name
UNKNOWN     28
            25
  dave      25
bob         12
CHARLIE      9
Grace        8
Eve          8
ERROR        3
NaN          2
Name: count, dtype: int64

*****Product_Category*****
Product_Category
unknown         32
HOME            26
 ElecTRONICS    21
  Toys          18
clothing        16
Clothing         4
 Electronics     3
Name: count, dtype: int64

*****Price (USD)*****
Price (USD)
$9.99      21
25.50      19
0.0        18
  50.5     14
100        13
ERROR      12
NaN        12
$19.99     11
Name: count, dtype: int64

*****Qty*****
Qty
3          24
-1         23
1          18
2          16
 4         11
five       11
10         11
UNKNOWN     5
NaN         1
Name: count, dtype: int64

*****Order_Date*****
Order_Date
04-08-2026    35
UNKNOWN       19
2026-08-01    19
08/02/2026    17
2026-08-05    12
2026/08/03    10
pending        8
Name: count, dtype: int64

#### Phase 2: Structural Cleaning

In [167]:
df.columns = df.columns.str.strip()

In [168]:
df = df.rename(columns = {"Customer Name":"Customer_Name","Order ID":"Order_ID","Price (USD)":"Price_USD"})

In [169]:
df

     Order_ID Customer_Name Product_Category Price_USD   Qty  Order_Date
0    ORD-2824       UNKNOWN      Electronics       100     4  08/02/2026
1    ORD-1409      Grace         Electronics       100     3  04-08-2026
2    ORD-5506           bob         Clothing       100  five  08/02/2026
3    ORD-5012       UNKNOWN         Clothing     ERROR     1  04-08-2026
4    ORD-4657       UNKNOWN          unknown    $19.99     2  2026/08/03
..        ...           ...              ...       ...   ...         ...
115  ORD-1773                           Toys     50.5      1  04-08-2026
116  ORD-3286           Eve        clothing     $19.99  five  04-08-2026
117  ORD-6679           bob      ElecTRONICS     25.50     3  04-08-2026
118  ORD-7940       UNKNOWN             HOME       0.0    -1  04-08-2026
119  ORD-7940       UNKNOWN             HOME       0.0    -1  04-08-2026

[120 rows x 6 columns]

In [170]:
df = df.drop_duplicates()

In [171]:
df.info()

<class 'pandas.DataFrame'>
Index: 114 entries, 0 to 115
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          113 non-null    str
 1   Customer_Name     112 non-null    str
 2   Product_Category  114 non-null    str
 3   Price_USD         102 non-null    str
 4   Qty               113 non-null    str
 5   Order_Date        114 non-null    str
dtypes: str(6)
memory usage: 6.2 KB

In [172]:
df.isnull().sum()

Order_ID             1
Customer_Name        2
Product_Category     0
Price_USD           12
Qty                  1
Order_Date           0
dtype: int64

In [173]:
for col in df.columns:
    print(f"*****{col}*****")
    print(df[col].value_counts(dropna = False))
    print()

*****Order_ID*****
Order_ID
ORD-3286    2
ORD-3406    2
ORD-9204    2
ORD-7685    2
ORD-5111    2
           ..
ORD-6987    1
ORD-6346    1
ORD-9069    1
ORD-5011    1
ORD-1773    1
Name: count, Length: 105, dtype: int64

*****Customer_Name*****
Customer_Name
UNKNOWN     25
            25
  dave      25
bob         11
CHARLIE      9
Grace        8
Eve          6
ERROR        3
NaN          2
Name: count, dtype: int64

*****Product_Category*****
Product_Category
unknown         31
HOME            23
 ElecTRONICS    20
  Toys          18
clothing        15
Clothing         4
 Electronics     3
Name: count, dtype: int64

*****Price_USD*****
Price_USD
$9.99      21
25.50      18
0.0        15
  50.5     14
100        13
NaN        12
ERROR      11
$19.99     10
Name: count, dtype: int64

*****Qty*****
Qty
3          22
-1         20
1          18
2          16
 4         11
10         11
five       10
UNKNOWN     5
NaN         1
Name: count, dtype: int64

*****Order_Date*****
Order_Date
04-08-2026    30
2026-08-01    19
UNKNOWN       18
08/02/2026    17
2026-08-05    12
2026/08/03    10
pending        8
Name: count, dtype: int64

#### Phase 3: Text & Value Standardization

In [174]:
df["Customer_Name"] = df["Customer_Name"].str.strip().str.title()

In [175]:
df["Product_Category"] = df["Product_Category"].str.strip().str.title()

In [176]:
junk_values = ["Error","Unknown",""]

In [177]:
df["Customer_Name"] = df["Customer_Name"].replace(junk_values,pd.NA)

In [178]:
df["Product_Category"] = df["Product_Category"].replace(junk_values,pd.NA)

In [179]:
target_tcol = ["Customer_Name", "Product_Category"]
for tcol in target_tcol:
    print(f"*****{tcol}*****")
    print(df[tcol].value_counts(dropna = False))
    print()

*****Customer_Name*****
Customer_Name
NaN        55
Dave       25
Bob        11
Charlie     9
Grace       8
Eve         6
Name: count, dtype: int64

*****Product_Category*****
Product_Category
NaN            31
Electronics    23
Home           23
Clothing       19
Toys           18
Name: count, dtype: int64

In [180]:
target_ncol = ["Qty","Price_USD"]
for ncol in target_ncol:
    print(f"*****{ncol}*****")
    print(df[ncol].value_counts(dropna = False))
    print()

*****Qty*****
Qty
3          22
-1         20
1          18
2          16
 4         11
10         11
five       10
UNKNOWN     5
NaN         1
Name: count, dtype: int64

*****Price_USD*****
Price_USD
$9.99      21
25.50      18
0.0        15
  50.5     14
100        13
NaN        12
ERROR      11
$19.99     10
Name: count, dtype: int64

In [181]:
df['Qty'] = df['Qty'].replace('five',5)

In [182]:
df['Qty'] = pd.to_numeric(df['Qty'],errors = 'coerce')

In [183]:
df.loc[df['Qty'] < 0,'Qty'] = pd.NA

In [184]:
df['Price_USD'] = df['Price_USD'].str.replace('$','',regex = False)

In [185]:
df['Price_USD'] = pd.to_numeric(df['Price_USD'],errors = 'coerce')

In [186]:
df[['Qty','Price_USD']].describe()

             Qty   Price_USD
count  88.000000   91.000000
mean    3.636364   31.600989
std     2.717258   32.080654
min     1.000000    0.000000
25%     2.000000    9.990000
50%     3.000000   19.990000
75%     4.000000   50.500000
max    10.000000  100.000000

In [187]:
df[['Qty','Price_USD']].info()

<class 'pandas.DataFrame'>
Index: 114 entries, 0 to 115
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Qty        88 non-null     float64
 1   Price_USD  91 non-null     float64
dtypes: float64(2)
memory usage: 2.7 KB

In [188]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors = 'coerce', format = 'mixed')

In [189]:
df['Order_Date'].info()

<class 'pandas.Series'>
Index: 114 entries, 0 to 115
Series name: Order_Date
Non-Null Count  Dtype
--------------  -----
88 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 1.8 KB